openapi: 3.0.3
info:
  title: HeNex V3
  description: This collection includes all the APIs of version 3 for HeNex
  version: 1.0.0
servers:
- url: https://api.diem-platform.com
paths:
  /api/v3/data/henexmarketresultsborderschedules/2021/10/29/3:
    post:
      summary: GR Market-Market Results BorderSchedules
      description: "false"
      operationId: rEST_Service3
      parameters:
      - name: x-auth-key
        in: header
        required: false
        schema:
          type: string
        example: "ASLDKJASDJK2534S"
      x-codegen-request-body-name: rest_service347request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/rest_service347request'
            example: {"interconnection":"AL-GR","direction":0,"market":"DAM"}
        required: false
      responses:
        200:
          description: Successful response
  /api/v3/data/henexmarketresultsborderschedulesall/2020/10/28/20:
    post:
      summary: GR Market-Market Results BorderSchedules All Interconnections
      description: "false"
      operationId: rEST_Service2
      parameters:
      - name: x-auth-key
        in: header
        required: false
        schema:
          type: string
        example: "ASLDKJASDJK2534S"
      x-codegen-request-body-name: rest_service149request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/rest_service149request'
            example: {"class":"Imports","direction":0,"market":"DAM"}
        required: false
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/REST_ServiceResponse224'
              example: '{"$schema":"http://json-schema.org/draft-04/schema#","type":"object","properties":{"meta":{"type":"object","properties":{"requestParams":{"type":"object","properties":{"year":{"type":"string"},"month":{"type":"string"},"day":{"type":"string"},"duration":{"type":"string"},"class":{"type":"string"},"market":{"type":"string"},"direction":{"type":"string"}}},"timezone":{"type":"string"},"offeringName":{"type":"string"},"updatedOn":{"type":"string"},"source":{"type":"string"}}},"data":{"type":"object","properties":{"MK-GR":{"type":"array","items":{"type":"object","properties":{"DateTime":{"type":"string"},"value":{"type":"number"},"ResolutionCode":{"type":"string"},"uom":{"type":"string"}},"required":["DateTime","value","ResolutionCode","uom"]}},"TR-GR":{"type":"array","items":{"type":"object","properties":{"DateTime":{"type":"string"},"value":{"type":"number"},"ResolutionCode":{"type":"string"},"uom":{"type":"string"}},"required":["DateTime","value","ResolutionCode","uom"]}},"AL-GR":{"type":"array","items":{"type":"object","properties":{"DateTime":{"type":"string"},"value":{"type":"number"},"ResolutionCode":{"type":"string"},"uom":{"type":"string"}},"required":["DateTime","value","ResolutionCode","uom"]}},"BG-GR":{"type":"array","items":{"type":"object","properties":{"DateTime":{"type":"string"},"value":{"type":"number"},"ResolutionCode":{"type":"string"},"uom":{"type":"string"}},"required":["DateTime","value","ResolutionCode","uom"]}},"IT-GR":{"type":"array","items":{"type":"object","properties":{"DateTime":{"type":"string"},"value":{"type":"number"},"ResolutionCode":{"type":"string"},"uom":{"type":"string"}},"required":["DateTime","value","ResolutionCode","uom"]}}}}}}'
  /api/v3/data/henexmarketresultsdemand/2021/10/28/20:
    post:
      summary: GR Market-Market Results Demand
      description: "false"
      operationId: rEST_Service
      parameters:
      - name: x-auth-key
        in: header
        required: false
        schema:
          type: string
        example: "ASLDKJASDJK2534S"
      x-codegen-request-body-name: rest_service14request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/rest_service14request'
            example: {"class":"CRETE LOAD","direction":1,"market":"DAM","meta":{"requestParams":{"year":"2021","month":"10","day":"28","duration":"20","class":"CRETELOAD","market":"DAM","direction":"BUY"}}}
        required: false
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/REST_ServiceResponse94'
              example: '{"$schema":"http://json-schema.org/draft-04/schema#","type":"object","properties":{"meta":{"type":"object","properties":{"requestParams":{"type":"object","properties":{"year":{"type":"string"},"month":{"type":"string"},"day":{"type":"string"},"duration":{"type":"string"},"class":{"type":"string"},"market":{"type":"string"},"direction":{"type":"string"}}},"timezone":{"type":"string"},"offeringName":{"type":"string"},"updatedOn":{"type":"string"},"source":{"type":"string"}}},"data":{"type":"object","properties":{"Load":{"type":"array","items":{"type":"object","properties":{"DateTime":{"type":"string"},"value":{"type":"number"},"ResolutionCode":{"type":"string"},"uom":{"type":"string"}},"required":["DateTime","value","ResolutionCode","uom"]}}}}}}'
  /api/v3/data/henexmarketresultsdemandpermarket/2020/10/28/500:
    post:
      summary: GR Market-Market Results Demand Per Market
      description: "false"
      operationId: rEST_Service12
      parameters:
      - name: x-auth-key
        in: header
        required: false
        schema:
          type: string
        example: "ASLDKJASDJK2534S"
      x-codegen-request-body-name: rest_service578request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/rest_service578request'
            example: {"direction":0,"class":"HV"}
        required: false
      responses:
        200:
          description: Successful response
  /api/v3/data/henexmarketresultsperproductiontechnology/2020/10/28/500:
    post:
      summary: GR Market-Market Results Per Production Technology
      description: "false"
      operationId: rEST_Service4
      parameters:
      - name: x-auth-key
        in: header
        required: false
        schema:
          type: string
        example: "ASLDKJASDJK2534S"
      x-codegen-request-body-name: rest_service372request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/rest_service372request'
            example: {"technology":"CRETE CONVENTIONAL","direction":0,"market":"DAM"}
        required: false
      responses:
        200:
          description: Successful response
  /api/v3/data/henexmarketresultsperproductiontechnologypermarket/2020/10/28/2000:
    post:
      summary: GR Market-Market Results Per Production Technology Per Market
      description: "false"
      operationId: rEST_Service5
      parameters:
      - name: x-auth-key
        in: header
        required: false
        schema:
          type: string
        example: "ASLDKJASDJK2534S"
      x-codegen-request-body-name: rest_service397request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/rest_service397request'
            example: {"technology":"CRETE CONVENTIONAL","direction":0}
        required: false
      responses:
        200:
          description: Successful response
  /api/v3/data/henexmarketresultsprices/2020/10/28/5:
    post:
      summary: GR Market-Market Results Prices
      description: "false"
      operationId: rEST_Service7
      parameters:
      - name: x-auth-key
        in: header
        required: false
        schema:
          type: string
        example: "ASLDKJASDJK2534S"
      x-codegen-request-body-name: rest_service444request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/rest_service444request'
            example: {"direction":0,"market":"DAM"}
        required: false
      responses:
        200:
          description: Successful response
  /api/v3/data/henexmarketresultspricespermarket/2020/10/28/20:
    post:
      summary: GR Market-Market Results Prices Per Market
      description: "false"
      operationId: rEST_Service6
      parameters:
      - name: x-auth-key
        in: header
        required: false
        schema:
          type: string
        example: "ASLDKJASDJK2534S"
      x-codegen-request-body-name: rest_service421request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/rest_service421request'
            example: {"direction":0}
        required: false
      responses:
        200:
          description: Successful response
  /api/v3/data/henexpremarketresultsborderschedules/2020/10/28/5:
    post:
      summary: GR Market-PreMarket Results BorderSchedules
      description: "false"
      operationId: rEST_Service8
      parameters:
      - name: x-auth-key
        in: header
        required: false
        schema:
          type: string
        example: "ASLDKJASDJK2534S"
      x-codegen-request-body-name: rest_service468request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/rest_service468request'
            example: {"direction":0,"interconnection":"AL-GR"}
        required: false
      responses:
        200:
          description: Successful response
  /api/v3/data/henexpremarketresultsborderschedulesall/2020/10/28/5:
    post:
      summary: GR Market-PreMarket Results BorderSchedules All Interconnections
      description: "false"
      operationId: rEST_Service9
      parameters:
      - name: x-auth-key
        in: header
        required: false
        schema:
          type: string
        example: "ASLDKJASDJK2534S"
      x-codegen-request-body-name: rest_service492request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/rest_service492request'
            example: {"direction":0,"class":"Import","market":"DAM","timezone":"CET"}
        required: false
      responses:
        200:
          description: Successful response
  /api/v3/data/henexpremarketresultsdemand/2020/10/28/5:
    post:
      summary: GR Market-PreMarket Results Demand
      description: "false"
      operationId: rEST_Service10
      parameters:
      - name: x-auth-key
        in: header
        required: false
        schema:
          type: string
        example: "ASLDKJASDJK2534S"
      - name: format
        in: query
        required: false
        schema:
          type: string
        example: '"csv"'
      - name: max
        in: query
        required: false
        schema:
          type: integer
          format: int32
        example: '"10"'
      x-codegen-request-body-name: rest_service518request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/rest_service518request'
            example: {"direction":1,"class":"LV","market":"DAM"}
        required: false
      responses:
        200:
          description: Successful response
  /api/v3/data/henexpremarketsummaryperproductiontechnology/2020/10/28/5:
    post:
      summary: GR Market-PreMarket Summary per Production Technology
      description: "false"
      operationId: rEST_Service11
      parameters:
      - name: x-auth-key
        in: header
        required: false
        schema:
          type: string
        example: "ASLDKJASDJK2534S"
      x-codegen-request-body-name: rest_service553request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/rest_service553request'
            example: {"direction":0,"technology":"Lignite","market":"DAM"}
        required: false
      responses:
        200:
          description: Successful response
components:
  schemas:
    rest_service347request:
      type: object
    rest_service14request:
      type: object
    rest_service397request:
      type: object
    REST_ServiceResponse94:
      type: object
    rest_service421request:
      type: object
    rest_service492request:
      type: object
    rest_service372request:
      type: object
    rest_service149request:
      type: object
    REST_ServiceResponse224:
      type: object
    rest_service444request:
      type: object
    rest_service553request:
      type: object
    rest_service468request:
      type: object
    rest_service578request:
      type: object
    rest_service518request:
      type: object
