openapi: 3.0.3
info:
  title: Supporting Calls
  description: This collection includes all the APIs of version 3 for Supporting Calls
  version: 1.0.0
servers:
- url: https://api.diem-platform.com
paths:
  /action:
    post:
      operationId: rEST_Service2
      responses:
        200:
          description: OK
