openapi: 3.0.0
info:
  title: Supporting Calls
  version: 1.0.0
servers:
  - url: https://api.diem-platform.com
paths:
  /api/v3/getCapabilities:
    get:
      tags:
        - General
      summary: getCapabilities
      parameters:
        - name: x-auth-key
          in: header
          schema:
            type: string
          example: ASLDKJASDJK2534S
      responses:
        '200':
          description: OK
          headers:
            X-Powered-By:
              schema:
                type: string
              example:
                value: Express
            Access-Control-Allow-Origin:
              schema:
                type: string
              example:
                value: '*'
            Access-Control-Allow-Headers:
              schema:
                type: string
              example:
                value: Origin, X-Requested-With, Content-Type, Accept, x-auth-token
            Access-Control-Allow-Methods:
              schema:
                type: string
              example:
                value: POST, GET, PUT, DELETE, OPTIONS
            Content-Type:
              schema:
                type: string
              example:
                value: application/json; charset=utf-8
            Content-Length:
              schema:
                type: integer
              example:
                value: '15795'
            ETag:
              schema:
                type: string
              example:
                value: W/"3db3-lkdkDcESXZZxbuX3AGdkIQMx5fs"
            Date:
              schema:
                type: string
              example:
                value: Mon, 09 May 2022 11:01:32 GMT
            Connection:
              schema:
                type: string
              example:
                value: keep-alive
          content:
            application/json:
              schema:
                type: object
              example:
                $schema: http://json-schema.org/draft-04/schema#
                type: array
                items:
                  type: object
                  properties:
                    diemID:
                      type: string
                    datasetClass:
                      type: string
                    datasetSubClass:
                      type: string
                    sources:
                      type: array
                      items:
                        type: object
                        properties:
                          sourceName:
                            type: string
                          datasetTitleEN:
                            type: string
                          offeringNameEndpoint:
                            type: string
                        required:
                          - sourceName
                          - datasetTitleEN
                          - offeringNameEndpoint
                  required:
                    - diemID
                    - datasetClass
                    - datasetSubClass
                    - sources
  /api/v3/getCapabilities/admieupliftaccounts:
    get:
      tags:
        - General
      summary: getCapabilities/offeringName
      parameters:
        - name: x-auth-key
          in: header
          schema:
            type: string
          example: ASLDKJASDJK2534S
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v3/data/areareference:
    get:
      tags:
        - General
      summary: areaReference
      parameters:
        - name: x-auth-key
          in: header
          schema:
            type: string
          example: ASLDKJASDJK2534S
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v3/data/areareference/SLOV:
    get:
      tags:
        - General
      summary: areaReference/area
      parameters:
        - name: x-auth-key
          in: header
          schema:
            type: string
          example: ASLDKJASDJK2534S
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v3/data/interconnections:
    get:
      tags:
        - General
      summary: interconnections
      parameters:
        - name: x-auth-key
          in: header
          schema:
            type: string
          example: ASLDKJASDJK2534S
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v3/data/interconnections/TR:
    get:
      tags:
        - General
      summary: interconnections/interconnection
      parameters:
        - name: x-auth-key
          in: header
          schema:
            type: string
          example: ASLDKJASDJK2534S
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v3/data/productiontypes:
    get:
      tags:
        - General
      summary: productiontypes
      parameters:
        - name: x-auth-key
          in: header
          schema:
            type: string
          example: ASLDKJASDJK2534S
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v3/data/productiontypes/ot:
    get:
      tags:
        - General
      summary: productiontypes/type
      parameters:
        - name: x-auth-key
          in: header
          schema:
            type: string
          example: ASLDKJASDJK2534S
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v3/data/generationunits/GREECE_IPTO_CA_CTA:
    get:
      tags:
        - General
      summary: generationunits/areaRef
      parameters:
        - name: x-auth-key
          in: header
          schema:
            type: string
          example: ASLDKJASDJK2534S
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v3/data/generationunits/GREECE_IPTO_CA_CTA/MEG:
    get:
      tags:
        - General
      summary: generationunits/areaRef/unitAbbrev
      parameters:
        - name: x-auth-key
          in: header
          schema:
            type: string
          example: ASLDKJASDJK2534S
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v3/data/ngpoints:
    get:
      tags:
        - General
      summary: ngpoints
      parameters:
        - name: x-auth-key
          in: header
          schema:
            type: string
          example: ASLDKJASDJK2534S
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
