openapi: 3.0.3
info:
  title: HeNex V3
  description: This collection includes all the APIs of version 3 for HeNex
  version: 1.0.0
servers:
- url: https://10.0.1.12/
paths:
  /api/v3/data/henexmarketresultsborderschedules/2021/10/29/3:
    post:
      description: null
      operationId: gR_Market-Market_Results_BorderSchedules
      parameters:
      - name: x-auth-key
        in: header
        required: false
        schema:
          type: string
        example: '"ASLDKJASDJK2534S"'
      x-codegen-request-body-name: rest_service73request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/rest_service73request'
            example: '{"interconnection":"AL-GR","direction":0,"market":"DAM"}'
        required: false
      responses:
        200:
          description: Successful response
  /api/v3/data/henexmarketresultsborderschedulesall/2020/10/28/20:
    post:
      description: null
      operationId: gR_Market-Market_Results_BorderSchedules_All_Interconnections
      parameters:
      - name: x-auth-key
        in: header
        required: false
        schema:
          type: string
        example: '"ASLDKJASDJK2534S"'
      x-codegen-request-body-name: rest_service48request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/rest_service48request'
            example: '{"class":"Imports","direction":0,"market":"DAM"}'
        required: false
      responses:
        200:
          description: Successful response
  /api/v3/data/henexmarketresultsdemand/2021/10/28/20:
    post:
      description: null
      operationId: gR_Market-Market_Results_Demand
      parameters:
      - name: x-auth-key
        in: header
        required: false
        schema:
          type: string
        example: '"ASLDKJASDJK2534S"'
      x-codegen-request-body-name: rest_service14request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/rest_service14request'
            example: '{"class":"CRETE LOAD","direction":1,"market":"DAM","meta":{"requestParams":{"year":"2021","month":"10","day":"28","duration":"20","class":"CRETE
              LOAD","market":"DAM","direction":"BUY"}}}'
        required: false
      responses:
        200:
          description: Successful response
  /api/v3/data/henexmarketresultsdemandpermarket/2020/10/28/500:
    post:
      description: null
      operationId: gR_Market-Market_Results_Demand_Per_Market
      parameters:
      - name: x-auth-key
        in: header
        required: false
        schema:
          type: string
        example: '"ASLDKJASDJK2534S"'
      x-codegen-request-body-name: rest_service304request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/rest_service304request'
            example: '{"direction":0,"class":"HV"}'
        required: false
      responses:
        200:
          description: Successful response
  /api/v3/data/henexmarketresultsperproductiontechnology/2020/10/28/500:
    post:
      description: null
      operationId: gR_Market-Market_Results_Per_Production_Technology
      parameters:
      - name: x-auth-key
        in: header
        required: false
        schema:
          type: string
        example: '"ASLDKJASDJK2534S"'
      x-codegen-request-body-name: rest_service98request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/rest_service98request'
            example: '{"technology":"CRETE CONVENTIONAL","direction":0,"market":"DAM"}'
        required: false
      responses:
        200:
          description: Successful response
  /api/v3/data/henexmarketresultsperproductiontechnologypermarket/2020/10/28/2000:
    post:
      description: null
      operationId: gR_Market-Market_Results_Per_Production_Technology_Per_Market
      parameters:
      - name: x-auth-key
        in: header
        required: false
        schema:
          type: string
        example: '"ASLDKJASDJK2534S"'
      x-codegen-request-body-name: rest_service123request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/rest_service123request'
            example: '{"technology":"CRETE CONVENTIONAL","direction":0}'
        required: false
      responses:
        200:
          description: Successful response
  /api/v3/data/henexmarketresultsprices/2020/10/28/5:
    post:
      description: null
      operationId: gR_Market-Market_Results_Prices
      parameters:
      - name: x-auth-key
        in: header
        required: false
        schema:
          type: string
        example: '"ASLDKJASDJK2534S"'
      x-codegen-request-body-name: rest_service170request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/rest_service170request'
            example: '{"direction":0,"market":"DAM"}'
        required: false
      responses:
        200:
          description: Successful response
  /api/v3/data/henexmarketresultspricespermarket/2020/10/28/20:
    post:
      description: null
      operationId: gR_Market-Market_Results_Prices_Per_Market
      parameters:
      - name: x-auth-key
        in: header
        required: false
        schema:
          type: string
        example: '"ASLDKJASDJK2534S"'
      x-codegen-request-body-name: rest_service147request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/rest_service147request'
            example: '{"direction":0}'
        required: false
      responses:
        200:
          description: Successful response
  /api/v3/data/henexpremarketresultsborderschedules/2020/10/28/5:
    post:
      description: null
      operationId: gR_Market-PreMarket_Results_BorderSchedules
      parameters:
      - name: x-auth-key
        in: header
        required: false
        schema:
          type: string
        example: '"ASLDKJASDJK2534S"'
      x-codegen-request-body-name: rest_service194request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/rest_service194request'
            example: '{"direction":0,"interconnection":"AL-GR"}'
        required: false
      responses:
        200:
          description: Successful response
  /api/v3/data/henexpremarketresultsborderschedulesall/2020/10/28/5:
    post:
      description: null
      operationId: gR_Market-PreMarket_Results_BorderSchedules_All_Interconnections
      parameters:
      - name: x-auth-key
        in: header
        required: false
        schema:
          type: string
        example: '"ASLDKJASDJK2534S"'
      x-codegen-request-body-name: rest_service218request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/rest_service218request'
            example: '{"direction":0,"class":"Import","market":"DAM","timezone":"CET"}'
        required: false
      responses:
        200:
          description: Successful response
  /api/v3/data/henexpremarketresultsdemand/2020/10/28/5:
    post:
      description: null
      operationId: gR_Market-PreMarket_Results_Demand
      parameters:
      - name: x-auth-key
        in: header
        required: false
        schema:
          type: string
        example: '"ASLDKJASDJK2534S"'
      - name: format
        in: query
        required: false
        schema:
          type: string
        example: '"csv"'
      - name: max
        in: query
        required: false
        schema:
          type: integer
          format: int32
        example: '"10"'
      x-codegen-request-body-name: rest_service244request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/rest_service244request'
            example: '{"direction":1,"class":"LV","market":"DAM"}'
        required: false
      responses:
        200:
          description: Successful response
  /api/v3/data/henexpremarketsummaryperproductiontechnology/2020/10/28/5:
    post:
      description: null
      operationId: gR_Market-PreMarket_Summary_per_Production_Technology
      parameters:
      - name: x-auth-key
        in: header
        required: false
        schema:
          type: string
        example: '"ASLDKJASDJK2534S"'
      x-codegen-request-body-name: rest_service279request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/rest_service279request'
            example: '{"direction":0,"technology":"Lignite","market":"DAM"}'
        required: false
      responses:
        200:
          description: Successful response
components:
  schemas:
    rest_service304request:
      type: object
      properties:
        direction:
          type: string
        class:
          type: string
    rest_service244request:
      type: object
      properties:
        direction:
          type: string
        class:
          type: string
        market:
          type: string
    rest_service194request:
      type: object
      properties:
        direction:
          type: string
        interconnection:
          type: string
    rest_service170request:
      type: object
      properties:
        direction:
          type: string
        market:
          type: string
    rest_service48request:
      type: object
      properties:
        class:
          type: string
        direction:
          type: string
        market:
          type: string
    rest_service123request:
      type: object
      properties:
        technology:
          type: string
        direction:
          type: string
    rest_service98request:
      type: object
      properties:
        technology:
          type: string
        direction:
          type: string
        market:
          type: string
    rest_service279request:
      type: object
      properties:
        direction:
          type: string
        technology:
          type: string
        market:
          type: string
    rest_service73request:
      type: object
      properties:
        interconnection:
          type: string
        direction:
          type: string
        market:
          type: string
    rest_service147request:
      type: object
      properties:
        direction:
          type: string
    rest_service14request:
      type: object
      properties:
        class:
          type: string
        direction:
          type: string
        market:
          type: string
        meta:
          type: string
    rest_service218request:
      type: object
      properties:
        direction:
          type: string
        class:
          type: string
        market:
          type: string
        timezone:
          type: string
